version: "3.8"

services:
  frontend_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: ${BACKEND_URL}
      NEXT_PUBLIC_BACKEND_URL: ${BACKEND_URL}

  backend_app:
    build:
      context: ../sentiment-analysis-back-end
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../sentiment-analysis-back-end/.env
    # environment:
    #   FRONTEND_URL: ${FRONTEND_URL}
